version: "3.9"
services:
  llama:
    image: vcalvi/llama-cpp-docker
    environment:
      - GGML_CUDA_NO_PINNED=1
      - LLAMA_CTX_SIZE=2048
      - LLAMA_MODEL=/models/*.gguf
      - LLAMA_N_GPU_LAYERS=99
    volumes:
      - ./models:/models
    ports:
      - target: 8080
        published: 8080
        mode: host
